// Türkisch und Englisch für die Spieleübersicht.
//
// **Deutsch steht nicht hier drin.** Es steht im HTML daneben, und `sprache.js`
// legt diese Fassungen nur darüber. Deshalb gibt es keine zweite Quelle für den
// deutschen Wortlaut, die auseinanderlaufen könnte – und ohne JavaScript bleibt
// die Seite vollständig deutsch statt leer.
//
// Die Schlüssel stehen als `data-t` (Text), `data-t-html` (Text mit
// Auszeichnung) und `data-t-attr` (Attribute) im Markup; ein paar wenige –
// `suche.*` und `dialog.alt` – werden vom Skript der Seite über `sprache.t()`
// geholt, weil ihr Text erst beim Tippen entsteht.
//
// `werkzeug/pruefe-sprache.mjs` gleicht beide Richtungen ab: kein Schlüssel im
// Markup ohne Übersetzung, keine Übersetzung ohne Schlüssel im Markup.
//
//   k.<spiel>.kurz     der Satz auf der Kachel
//   k.<spiel>.lang     der Absatz im Anleitungsdialog
//   k.<spiel>.s1…      die Schritte im Dialog (stehen im <template>)
//   tag.*              die Marken auf den Kacheln, nach Inhalt statt je Kachel
//   gruppe.*           die Kategorien
//   ui.*, dialog.*, suche.*, melden.*, spende.*, fuss.*, seite.*
//
// **Die Spielnamen werden nicht übersetzt.** Der Name ist die Adresse und das,
// was auf dem Bildschirm des Spiels steht; eine übersetzte Kachel führte sonst
// zu einem Spiel, das anders heißt. Was es ist, sagt der Satz darunter.
// Ebenso bleiben die Alternativtexte der Bilder deutsch: die Screenshots zeigen
// deutsche Oberflächen, solange die Spiele selbst noch nicht übersetzt sind.

export const WOERTER = {
  tr: {
    // --- Kopf der Seite ---
    "seite.titel": "Oyunlar – inf-zeus.de",
    "seite.beschreibung": "1 ile 20 kişi için yirmi dokuz tarayıcı oyunu. Kurulum yok, hesap yok.",
    "seite.h1": "Oyunlar",
    "seite.sub": "1 ile 20 kişi için yirmi dokuz tarayıcı oyunu. İndirme yok, hesap yok – bağlantıyı paylaş, adını yaz, başla.",

    // --- Suche - die drei Meldungen entstehen erst beim Tippen ---
    "suche.platz": "Oyun ara – ad, anahtar kelime, kişi sayısı",
    "suche.label": "Oyunlarda ara",
    "suche.keins": "Oyun bulunamadı. Belki başka türlü yazılıyordur?",
    "suche.eins": "Tek oyun – Enter tuşu onu açar.",
    "suche.viele": "{alle} oyundan {n} tanesi.",

    // --- Die Kategorien ---
    "gruppe.beliebt.titel": "En çok oynananlar",
    "gruppe.beliebt.sub": "Burada ne yazacağına son dört hafta karar verir – ve ancak bir oyun belirgin biçimde daha sık açıldığında değişir.",
    "gruppe.runde.titel": "Masada, herkes kendi telefonuyla",
    "gruppe.runde.sub": "Siz oturup konuşuyorsunuz; telefon yalnızca sayıyor. Biri oda açar, diğerleri kodu yazar.",
    "gruppe.ruhe.titel": "Sırayla, acele etmeden",
    "gruppe.ruhe.sub": "Biri oynar, diğerleri birlikte düşünür. Kendi ayarladığınız düşünme süresi dışında zaman baskısı yok – onu da kapatabilirsiniz.",
    "gruppe.tempo.titel": "Hız ve beceri",
    "gruppe.tempo.sub": "Kartlar, semboller, refleksler. Kısa turlar, acımasız puanlar – herkes kendi cihazında.",
    "gruppe.allein.titel": "Tek başına",
    "gruppe.allein.sub": "Oda yok, kod yok, ikna edilecek kimse yok. Bulmaca oyunları tamamen tarayıcıda çalışır ve sayfa yüklendikten sonra bağlantıya ihtiyaç duymaz; Ameisen ile Glückspilz ise sürekli çalışır, çünkü yuvan ve hesabın sunucuda durur.",

    // --- Der Anleitungsdialog ---
    "dialog.zu": "Kapat",
    "dialog.bild": "Gerçek bir oyundan alınmış ekran görüntüsü.",
    "dialog.ablauf": "Bir tur nasıl geçer",
    "dialog.spielen": "Hemen oyna →",
    "dialog.melden": "🐞 Bu oyundaki hatayı bildir",
    "dialog.alt": "{spiel} oyunundan bir ekran görüntüsü",

    // --- Bugreport-Zeile ---
    "melden.text": "Bir şey mi bozuldu? Hatayı bildir – ve nelerin bildirildiğine bak.",
    "melden.go": "Hata bildirimi →",

    // --- Spendenknopf und sein Dialog ---
    "spende.text": "Oyunlar ücretsiz ve reklamsız. İsteyen sunucunun masrafına katkıda bulunabilir.",
    "spende.go": "Destek ol →",
    "spende.titel": "Denediğin için teşekkürler!",
    "spende.eins": "Bağış henüz kurulmadı – düğme benden hızlı davrandı. Yine de bastığın için içtenlikle sevindim.",
    "spende.zwei": "Sonra tekrar uğra. O zamana kadar en iyi katkı: yanında oynayacak birini getirmek.",
    "spende.zu": "Rica ederim",

    // --- Fusszeile ---
    "fuss.text": "Telefonda ve bilgisayarda, aynı Wi-Fi ağında ya da internet üzerinden çalışır. Bir cihaz odayı açar, diğerleri kodla katılır – herkes kendi cihazında oynar.",
    "fuss.impressum": "Künye",
    "fuss.datenschutz": "Gizlilik",
    "fuss.rechtsprache": "Künye ve gizlilik metni yalnızca Almanca mevcuttur.",

    // --- Was auf jeder Kachel steht ---
    "ui.spielen": "Oyna →",
    "ui.anleitung": "Kurallar",
    "ui.anleitungLabel": "Bu oyunun kuralları",

    // --- Die Marken - nach Inhalt, nicht je Kachel ---
    "tag.p1_4": "1–4 oyuncu",
    "tag.p1_6": "1–6 oyuncu",
    "tag.p1_20": "1–20 oyuncu",
    "tag.p2_4": "2–4 oyuncu",
    "tag.p2_6": "2–6 oyuncu",
    "tag.p2_8": "2–8 oyuncu",
    "tag.p2_10": "2–10 oyuncu",
    "tag.p3_6": "3–6 oyuncu",
    "tag.p3_10": "3–10 oyuncu",
    "tag.p4_12": "4–12 oyuncu",
    "tag.allein": "tek kişilik",
    "tag.auchallein": "tek de oynanır",
    "tag.karten": "kart",
    "tag.offline": "çevrimdışı",
    "tag.party": "parti",
    "tag.knobeln": "bulmaca",
    "tag.bluff": "blöf",
    "tag.ab18": "isteğe bağlı 18+",
    "tag.klassiker": "klasik",
    "tag.laeuftimmer": "hep çalışır",
    "tag.rollen": "roller",
    "tag.woerter": "kelimeler",
    "tag.reaktion": "refleks",
    "tag.gegeneinander": "karşılıklı",
    "tag.glueck": "şans &amp; sinir",
    "tag.wuerfel": "zar",
    "tag.trinkfrei": "içkisiz",
    "tag.merken": "hafıza",
    "tag.augen": "göz &amp; hız",
    "tag.tempo": "hız",
    "tag.taeglich": "günlük",
    "tag.zusehen": "izlemelik",

    // --- Die Kacheln ---
    "k.keep.kurz": "Bir makine, beş tur ve her seferinde daralan bir saat.",
    "k.keep.lang": "Çevir, tut, birleştir. Gitgide kısalan beş tur – en değerli kombinasyonu koyan masayı toplar.",
    "k.keep.s1": "Oda aç, bağlantıyı ilet – iki ile dört kişi. Tek başına da olur: başlat düğmesi kimseyi beklemez.",
    "k.keep.s2": "Beş tur, ve her biri bir öncekinden kısa: 90 saniyeden 25 saniyeye iner.",
    "k.keep.s3": "Silindir kendiliğinden döner. Ardından iki kez yenileme hakkın var; arada hangi sembollerin kalacağına sen karar verirsin.",
    "k.keep.s4": "Ortadakilerden geçerli bir kombinasyon seç. Puan, ne kadar nadir olduğuna bağlıdır – beşli, üçlünün yirmi katını öder, hem de her renkte. Sembol yalnızca küçük bir ek verir: kupa yüzde dört, yonca binde iki.",
    "k.keep.s5": "Saatin altında ikinci bir çubuk yanar. Sürekli düşer ve her kombinasyonla dolar, nadir olanlarla daha çok – bir beşli onu tamamen doldurur. Ne kadar sıcaksa çarpan o kadar büyür, iki katına kadar.",
    "k.keep.s6": "Hızlı oynayan onu yukarıda tutar: çevik bir hamlenin götürdüğü koru, bir üçlünün getirdiğinden azdır. Artık bir şey bulamıyorsan tur biter.",

    "k.cardchaos.kurz": "Üç kart piramidi, on tur ve sonunda kumar oynama hakkı.",
    "k.cardchaos.lang": "Üç piramit, bir kronometre, on tur. En hızlı zincir kuran kuleleri devirir.",
    "k.cardchaos.s1": "Masa aç, dört haneli kodu ilet – iki ile dört kişi. Tek başına da olur: o zaman kendi rekorunla yarışırsın.",
    "k.cardchaos.s2": "Herkes aynı saate karşı kendi tahtasını aynı anda oynar.",
    "k.cardchaos.s3": "Açık bir kart, yığındakinin tam bir üstü ya da bir altıysa oynanır. Papaz, as ve iki burada başa döner.",
    "k.cardchaos.s4": "Uyan kart kalmadıysa yeni kart çekersin – bu da zincirini götürür.",
    "k.cardchaos.s5": "Zincir uzadıkça çarpan büyür. Tur bitince puanının yarısını yazı turaya yatırabilirsin.",

    "k.nochnie.kurz": "Biri itiraf eder, geri kalanı yakalanır. Burada tuşa değil, ağıza yaslanan tek oyun.",
    "k.nochnie.lang": "Masadaki sohbet oyunu: biri itiraf eder, diğerleri yakalanır. Zaman baskısı yok, refleks yok – sadece konuşmak. Masum kartlar öntanımlıdır, 18+ için masa kendi izin verir.",
    "k.nochnie.s1": "Oda aç, bağlantıyı ilet – iki ile sekiz kişi, herkes kendi telefonuyla.",
    "k.nochnie.s2": "Her turda sunucu birini seçer. O kişi „Ben hiç …“ diye başlayan ve kendisi için doğru olan bir cümleyi yüksek sesle söyler.",
    "k.nochnie.s3": "Aklına bir şey gelmezse „Aklıma gelmiyor“ tuşuna basar ve bir kart alır – onu herkes görür.",
    "k.nochnie.s4": "Diğerleri itiraf eder: „Yaptım“ ya da „Hiç yapmadım“. Kimse kopya çekmesin diye herkes basmadan açılmaz.",
    "k.nochnie.s5": "Yakalanan listede kırmızı durur. Bunun bir yudum mu, bir hikâye mi yoksa hiçbir şey mi olacağına siz karar verirsiniz – oyun yalnızca sayar.",
    "k.nochnie.s6": "Kartlarda ne yazacağını oda sahibi seçer: masum, karışık ya da yalnızca 18+. 18+ kartlardan önce her cihaz bir kez sorar.",

    "k.minenfeld.kurz": "Sayıları oku, bayrak dik, tahmin etme. İlk dokunuş her zaman güvenlidir.",
    "k.minenfeld.lang": "Klasik oyun telefona taşındı: dokunmak açar, basılı tutmak bayrak diker. Üç boyut, her boyut için ayrı rekor. Tamamen tarayıcıda çalışır, hesapsız ve sunucusuz.",
    "k.minenfeld.s1": "Boyutu seç: küçük, orta ya da büyük.",
    "k.minenfeld.s2": "Dokunmak bir kareyi açar. İlk dokunuş asla mayına gelmez.",
    "k.minenfeld.s3": "Her sayı, çevresindeki sekiz karede kaç mayın olduğunu söyler.",
    "k.minenfeld.s4": "Basılı tutmak bayrak diker – bilgisayarda sağ tık da olur.",
    "k.minenfeld.s5": "Açık bir sayıya dokunmak, yeterince bayrak dikildiyse çevresini açar.",
    "k.minenfeld.s6": "Mayınsız tüm kareler açıldıysa bitti. Rekorun tarayıcında kalır.",

    "k.amehesten.kurz": "Tek soru, herkes aynı anda gösterir. Asıl sohbet, açıldıktan sonra başlar.",
    "k.amehesten.lang": "Bir soru, ve herkes aynı anda birini gösterir. Herkes seçmeden açılmaz – sonra çubuklar kimin kaç kez, kim tarafından işaret edildiğini gösterir. Hepsinin içinde en hızlı başlayanı. Masum sorular öntanımlıdır, 18+ için masa kendi izin verir.",
    "k.amehesten.s1": "Oda aç, bağlantıyı ilet – üç ile on kişi, herkes kendi telefonuyla.",
    "k.amehesten.s2": "Her turda „Hanginiz …?“ cümlesini tamamlayan bir soru gelir. Altında odadaki bütün adlar durur.",
    "k.amehesten.s3": "Herkes aynı anda en çok kime uyuyorsa ona dokunur – oda sahibi izin verdiyse kendine de.",
    "k.amehesten.s4": "Herkes bitirmediği sürece fikrini değiştirebilirsin. Kendi seçimin görünür kalır, başkalarınınki değil.",
    "k.amehesten.s5": "Ancak herkes seçtikten sonra açılır. Sonra çubuklar gelir: kim kaç oy almış – ve kimden.",
    "k.amehesten.s6": "Her oy, seçilen kişiye bir puandır; turu önde bitiren bir taç alır. Sonunda en çok kimin konuşulduğu ortaya çıkar.",
    "k.amehesten.s7": "Dört deste: Masum aile masasına uyar, Arsız huylara ve utanç anlarına nişan alır, Karışık ikisi birden – 18+ ise oda sahibinin açması gereken ayrı bir destedir.",

    "k.imposter.kurz": "Kelimeyi herkes bilir. Biri hariç – ve o, biliyormuş gibi yapmak zorunda.",
    "k.imposter.lang": "Herkes aynı kelimeyi alır – biri hariç. Telefon yalnızca kelimeyi gösterir, başka hiçbir şeyi düzenlemez: sırayla konuşmak, birbirini göstermek ve tartışmak masada olur. İkinci türde herkes bir kelime alır, ama biri farklıdır – ve o kişi bunu kendisi de bilmez. Hepsinin içinde en uzun süren akşam.",
    "k.imposter.s1": "Oda aç, bağlantıyı ilet – bir masada üç ile on kişi, herkes kendi telefonuyla. Hazır bildirimi yok: odadaki herkes oyundadır.",
    "k.imposter.s2": "Telefonu bıraktın, telefon geldi, şarj bitti? Yerin ayrılı kalır. Geri dönen yine aynı kişidir – aynı kartla, aynı turda.",
    "k.imposter.s3": "Oda sahibi „Dağıt“a dokunur. Herkes aynı kelimeyi alır, örneğin „zımpara kâğıdı“. Biri almaz – o yalnızca imposter olduğunu görür. Fazlasını da almaz.",
    "k.imposter.s4": "Kart <b>kapalı</b> durur: görmek için kapağı yukarı itip tut, bırakınca yine kapanır. Telefon açık kalabilir – hatta açık kalması daha iyidir, yoksa bağlantı kopar.",
    "k.imposter.s5": "Üstte <b>kimin başlayacağı ve hangi yöne gidileceği</b> yazar. Herkes aynı cümleyi okur; yine de telefon kimseye sıranın onda olduğunu söylemez – sayım masada yapılır.",
    "k.imposter.s6": "Sırayla herkes yüksek sesle bir kelime söyler.",
    "k.imposter.s7": "Fazla açık etme, yoksa imposter hemen anlar – ama fazla belirsiz de olma, yoksa asıl seni ondan sanırlar.",
    "k.imposter.s8": "Sonunda birbirinizi gösterirsiniz. Yüksek sesle, aynı anda, nasıl isterseniz. Telefon oy vermez ve puan tutmaz.",
    "k.imposter.s9": "Oda sahibi „Aç“a dokunur: herkes kimin olduğunu ve kelimenin ne olduğunu görür. Sonra yeniden dağıtır.",
    "k.imposter.s10": "<b>İkinci tür, „İki Kelime“:</b> herkes bir kelime alır, ama biri farklıdır – kiminde müze, birinde genelev. Kimin farklı olduğunu kimse bilmez, farklı olan da bilmez. Herkes iyi niyetle konuşur ve bir şeylerin uymadığı anlaşılana kadar zaman geçer.",
    "k.imposter.s11": "Çiftler bilerek tuhaftır: tarifler ikisine de uyar, anlamlarıysa birbirinden çok uzaktır. Masum öntanımlıdır, 18+ için oda sahibi izin verir – her cihaz öncesinde bir kez sorar.",

    "k.maexchen.kurz": "Zar atılır ki yalan söylenebilsin. İki zar, bir kupa, ve altını yalnızca sen görürsün.",
    "k.maexchen.lang": "Kupanın altında iki zar, ve onları yalnızca sen görürsün. Sözde ne attığını söyle – senden öncekinden yüksek olsun. Sıradaki ya inanır ya açar. Bu işten biri her zaman bir can kaybeder.",
    "k.maexchen.s1": "Oda aç, bağlantıyı ilet – iki ile sekiz kişi, herkes kendi telefonuyla.",
    "k.maexchen.s2": "Sırası gelen kupayı sallar. İki zar yalnızca onun ekranında görünür – sunucu bunu başka kimseye söylemez.",
    "k.maexchen.s3": "Sonra sözde ne attığını söyler. Söylediği, öncekini geçmek zorundadır; kendi atışına uyup uymadığı onun bileceği iştir.",
    "k.maexchen.s4": "Sıradaki karar verir: „İnanıyorum“ – o zaman kendi atar ve daha yükseğini söylemek zorunda kalır. Ya da „İnanmıyorum“ – o zaman açılır.",
    "k.maexchen.s5": "Açılışta her zaman bir taraf can kaybeder: yalan söylenmişse söyleyen, doğruysa şüphelenen.",
    "k.maexchen.s6": "Sıralama: en kötüsü 31, oradan yukarı 65'e kadar, üstünde çiftler. En tepede 21 durur – Mäxchen. Geçilemez, yalnızca şüphelenilebilir, o da iki katına mal olur.",
    "k.maexchen.s7": "Canı kalmayan çıkar. Masada kalan son kişi kazanır.",

    "k.flasche.kurz": "Sıranın kimde olduğuna şişe karar verir – bütün telefonlarda aynı anda.",
    "k.flasche.lang": "Sırayla biri şişeyi çevirir – şişe bütün ekranlarda aynı anda döner ve herkeste aynı kişide durur. Ardından doğruluk mu cesaret mi. Ya da yeterliyse yalnızca şişe.",
    "k.flasche.s1": "Oda aç, bağlantıyı ilet – üç ile on kişi, herkes kendi telefonuyla.",
    "k.flasche.s2": "Sırayla biri şişeyi çevirir. Şişe herkeste aynı anda döner ve her yerde aynı kişide durur – hedefi sunucu belirler, senin cihazın değil.",
    "k.flasche.s3": "Şişe kime denk gelirse sıra ondadır. „Yalnızca çevir“ modunda tur burada biter; sonrasını kendiniz halledersiniz.",
    "k.flasche.s4": "Diğer türlü, seçilen kişi doğruluk ile cesaret arasında seçim yapar ve bir kart alır. Onu herkes görür.",
    "k.flasche.s5": "Kart uymazsa tek dokunuşla başkası gelir. Pas geçmek her zaman serbesttir ve bir şeye mal olmaz – yalnızca sayılır.",
    "k.flasche.s6": "Kartlarda alkol, cinsellik ve bedensel temas yoktur. Buradaki „arsız“ utandırıcı demektir, müstehcen değil, ve her görev oturarak yapılabilir.",
    "k.flasche.s7": "Sonunda şişenin en çok kime denk geldiği yazar.",

    "k.werwolf.kurz": "Geceleri kurtlar birini alır. Gündüz köy konuşur – ve yanılır.",
    "k.werwolf.lang": "Dört ile on iki kişi, beş rol: kurt adam, köylü, kâhin, cadı, Amor. Anlatıcıyı sunucu üstlenir, sizin işiniz konuşmak ve birbirinizden şüphelenmek.",
    "k.werwolf.s1": "Oda aç, bağlantıyı ilet – dört kişiden başlar, altıdan sonra tadına varılır.",
    "k.werwolf.s2": "Herkes rol kartını kendi telefonunda alır ve onaylar.",
    "k.werwolf.s3": "Geceleri sunucu önce kurtları, sonra kâhini ve cadıyı uyandırır. Sırası olmayan telefonu bırakır.",
    "k.werwolf.s4": "Sabah sunucu geceyi kimin atlatamadığını söyler – ve hangi rolde olduğunu.",
    "k.werwolf.s5": "Gündüz konuşulur, yüksek sesle ve odada. Sonra herkes kimin asılacağını oylar.",
    "k.werwolf.s6": "Kurtlar bitince köy kazanır, sayıca üstün gelirlerse kurtlar kazanır. Âşıklar ikisi birlikte kazanır.",

    "k.becher.kurz": "Herkesin kupası altında beş zar. Teklif, masada olabilecek her şeyin üstüne verilir.",
    "k.becher.lang": "Mäxchen'in akrabası, ama herkesin kendi zarları var: „dört tane beş“ demek, kimde olursa olsun en az dört tane beş var demektir. Birler jokerdir. İnanmayan şüphelenir, ve biri bir zar kaybeder.",
    "k.becher.s1": "Oda aç, bağlantıyı ilet – iki ile altı kişi.",
    "k.becher.s2": "Herkes beş zar alır, yalnızca kendi telefonunda görünür.",
    "k.becher.s3": "Sırayla teklif verilir: adet ve sayı, her zaman öncekinden yüksek.",
    "k.becher.s4": "Birler her sayı için joker sayılır – birlerin kendisine teklif verilmez.",
    "k.becher.s5": "Teklif vermek yerine şüphelenebilirsin. O zaman herkes açar ve sayılır.",
    "k.becher.s6": "Yanılan bir zar kaybeder. Zarı kalmayan çıkar.",

    "k.kingscup.kurz": "Bir kart, bir kural, bütün masa uyar. Öntanımlı hâli içkisizdir.",
    "k.kingscup.lang": "Sırayla biri kart çeker ve herkes aynı kuralı kendi telefonunda görür. Öntanımlı olan içkisiz sürümdür: aynı kartlar, yudum yerine küçük görevler. Dördüncü papazda oyun biter.",
    "k.kingscup.s1": "Oda aç, bağlantıyı ilet – iki ile on kişi.",
    "k.kingscup.s2": "Oda sahibi sürümü seçer: içkisiz (öntanımlı) ya da yudumlu.",
    "k.kingscup.s3": "Sırayla biri kart çeker. Herkes onu kuralıyla birlikte aynı anda görür.",
    "k.kingscup.s4": "Sayılar kısa görevlerdir; vale, kız ve as kalıcı kurallar koyar.",
    "k.kingscup.s5": "Kural yerine getirilince kartı çeken „devam“a basar.",
    "k.kingscup.s6": "Dördüncü papazda tur biter.",

    "k.wortleger.kurz": "Puanlı harfler, bonus kareli bir tahta. Denetim kelime listesine göre yapılır, oyuncuların sabrına göre değil.",
    "k.wortleger.lang": "Rafta yedi taş, bonus kareli 13×13 bir tahta. Kelimeler dizin, başkalarınınkini kesin ve üç katlı kareleri başkası kapmadan alın.",
    "k.wortleger.s1": "Oda aç, kodu ilet – iki ile dört kişi. Herkes yalnızca kendi gördüğü yedi taş çeker.",
    "k.wortleger.s2": "Sırayla oynanır. Raftaki taşa dokun, boş kareye dokun – taş oraya iner. Tekrar dokunmak geri alır.",
    "k.wortleger.s3": "İlk kelime ortadaki yıldızdan geçmek zorundadır. Sonraki her kelime, tahtada duran bir şeye bağlanmalıdır.",
    "k.wortleger.s4": "Bir hamle, taşları boşluksuz olarak bir satıra ya da bir sütuna koyar. Bu sırada oluşan her şey – çaprazlamasına olanlar da – kelime olmak zorundadır.",
    "k.wortleger.s5": "Denetim, 488&nbsp;344 kayıtlı Almanca bir kelime listesine göre yapılır. Ä, ö, ü'nün kendi taşları vardır, ß ise SS diye yazılır.",
    "k.wortleger.s6": "Bonus kareler harfi ya da kelimeyi iki veya üç katına çıkarır – ama yalnızca kapatıldıkları hamlede.",
    "k.wortleger.s7": "Yedi taşın hepsini bir hamlede kullanmak 40 puan getirir. Bir şey bulamayan taş değiştirir ya da pas geçer.",
    "k.wortleger.s8": "Torbada iki joker vardır. Her harfin yerine geçerler ama sıfır puan sayarlar.",
    "k.wortleger.s9": "Torba boşken rafını ilk bitiren, diğerlerinin elinde kalanları puan olarak alır – onlar da kalan taşlarını düşer.",

    "k.luegen.kurz": "Kapalı at ve ne attığını söyle. İnanmayan açar – biri desteyi alır.",
    "k.luegen.lang": "Bütün deste dağıtılır, herkes kartlarından kurtulmak ister. Kartlar kapalı atılır, söylenen sıra her turda bir basamak yükselir. Gerçekten üç tane sekiz atıp atmadığını kimse görmez.",
    "k.luegen.s1": "Oda aç, bağlantıyı ilet – üç ile altı kişi, herkes kendi telefonuyla.",
    "k.luegen.s2": "Bütün kartlar dağıtılır. Kartları ilk biten kazanır.",
    "k.luegen.s3": "Sırayla herkes bir ile dört kart kapalı atar ve sözde ne olduğunu söyler.",
    "k.luegen.s4": "Söylenen sıra her turda bir basamak yükselir – elinde olsun olmasın, sıradakini atmak zorundasın.",
    "k.luegen.s5": "İnanmayan „Yalan!“a basar. Açılır: atan yalan söylediyse desteyi o alır, söylemediyse şüphelenen alır.",
    "k.luegen.s6": "As devredilmez – ondan sonra sıradaki yeni bir sıralamaya başlar.",

    "k.maumau.kurz": "Renge ya da sayıya uy. Yedi çektirir, sekiz pas geçirir, vale renk seçer.",
    "k.maumau.lang": "32 kartlık, telif dışı klasik. Hangi özel kuralların geçerli olacağını oda sahibi önceden ayarlar – ve tek karta düşen „Mau“ demek zorundadır, yoksa iki karta mal olur.",
    "k.maumau.s1": "Oda aç, bağlantıyı ilet – iki ile altı kişi.",
    "k.maumau.s2": "Oda sahibi özel kuralları açıp kapatır: yedi iki çektirir, sekiz pas geçirir, vale renk seçer.",
    "k.maumau.s3": "Herkes beş kart alır. Üstteki kartın rengine ya da sayısına uyulur.",
    "k.maumau.s4": "Uyan kart yoksa bir kart çekersin ve hamlen biter.",
    "k.maumau.s5": "Tek karta düşen, önceden „Mau!“ der. Unutmak iki karta mal olur.",
    "k.maumau.s6": "Kartları ilk biten kazanır; diğerleri kalanlarını sayar.",

    "k.schwimmen.kurz": "Üç kart, üç can. En azı kimdeyse bir can kaybeder.",
    "k.schwimmen.lang": "Tek renkte 31, elde üç kart, ortada açık üç kart. Değiştir, pas geç ya da masaya vur – ve umut et ki birinin eli seninkinden düşük olsun.",
    "k.schwimmen.s1": "Oda aç, bağlantıyı ilet – iki ile altı kişi.",
    "k.schwimmen.s2": "Herkes üç kart alır, üç kart da ortada açık durur.",
    "k.schwimmen.s3": "Tek renkteki en yüksek toplam sayılır: 7'den 10'a kadar yazdığı gibi, vale ile papaz on, as on bir. Aynı sayıdan üç tane 30,5 eder.",
    "k.schwimmen.s4": "Sırası gelen bir kart değiştirir, üçünü birden değiştirir – ya da pas geçer.",
    "k.schwimmen.s5": "Masaya vurmak şu demektir: herkesin bir hamlesi daha var, sonra açılır.",
    "k.schwimmen.s6": "Eli en düşük olan bir can kaybeder. Üçüncüden sonra „yüzmeye“ başlarsın, bir sonrakinde çıkarsın.",

    "k.paare.kurz": "Tek tahta, herkes izler, sıra birindedir. İki eşi bulan yeniden oynar.",
    "k.paare.lang": "Masa için hafıza oyunu: ortak bir tahta, herkes onu kendi telefonunda görür. Kapalı kartları senin tarayıcın da bilmez – kaynak koda bakmak işe yaramaz. Sekiz, on beş ya da yirmi dört çift; tek başına da oynanır.",
    "k.paare.s1": "Oda aç, bağlantıyı ilet – altı kişiye kadar, tek başına da olur.",
    "k.paare.s2": "Oda sahibi boyutu seçer: 8, 15 ya da 24 çift.",
    "k.paare.s3": "Sırası gelen iki kart açar. Herkes aynı tahtayı aynı anda görür.",
    "k.paare.s4": "Kartlar eşleşirse senindir – ve yeniden oynarsın.",
    "k.paare.s5": "Eşleşmezlerse herkes yerlerini aklında tutabilsin diye kısa süre açık kalırlar.",
    "k.paare.s6": "Sonunda en çok çifti olan kazanır.",

    "k.cubes.kurz": "Dolu bir ızgara, içinde senin rengin. Başkalarınınkine dokunamazsın.",
    "k.cubes.lang": "Herkes bir renk alır. Izgara her zaman doludur ve sürekli değişir – kendi karelerine, kaybolmadan yetiş. Üç tur, her birinde yeni bir kötülük.",
    "k.cubes.s1": "Oda aç, kodu ilet – iki ile altı kişi. Herkes kendi rengini alır.",
    "k.cubes.s2": "Herkes aynı ızgarayı görür. Yalnızca kendi rengindeki karelere dokunabilirsin; yabancılar soluktur ve tepki vermez.",
    "k.cubes.s3": "Izgara her zaman doludur – her boşluk anında dolar ve yarısı başkalarınındır. Kendi karelerini bulmak işin yarısıdır.",
    "k.cubes.s4": "<b>1. tur – Dokunma:</b> kendi karelerin kendiliğinden belirir ve yine kaybolur. Zamanında dokunan puanı alır. Alttaki çubuk daha ne kadar duracağını gösterir.",
    "k.cubes.s5": "<b>2. tur – Çoklu:</b> aynısı, ama her kare iki ile dört dokunuş ister. Puan ancak sonuncusunda gelir – yarısı silinmiş kare saymaz.",
    "k.cubes.s6": "<b>3. tur – Artı ve eksi:</b> artık içlerinde sayılar var, eksiler de dahil. Artılara dokun, eksileri bırak: onlar kendiliğinden gider.",
    "k.cubes.s7": "Eksiler artılara benzer – yalnızca sayı ele verir. Tam da bu yüzden telaşta yanlış kareye basılır.",
    "k.cubes.s8": "Kimse senin eksi karene basamaz – buna sunucu karar verir, başkalarının nezaketi değil.",
    "k.cubes.s9": "Sonunda bütün turların puanları toplanır.",

    "k.seconds.kurz": "İki kart, her zaman tam olarak bir ortak sembol. Önce sen bul.",
    "k.seconds.lang": "Senin kartın ile ortadaki kartın tam olarak bir ortak sembolü vardır. Ona ilk dokunan puanı alır.",
    "k.seconds.s1": "Oda aç, bağlantıyı ilet – iki ile dört kişi.",
    "k.seconds.s2": "Ortada bir kart durur, önünde de kendi kartın.",
    "k.seconds.s3": "İkisinin her zaman tam olarak bir ortak sembolü vardır – ne eksik ne fazla. Bu şans değil, destenin kuruluşundan gelir.",
    "k.seconds.s4": "Kendi kartında ona ilk dokunan puanı alır ve hemen yeni kart gelir.",
    "k.seconds.s5": "Yanlış dokunuş bir buçuk saniye engel demektir; o sırada diğerleri oynamayı sürdürür. Hedef puana ilk ulaşan kazanır.",

    "k.luckyreflex.kurz": "Hızlı olmak yetmez – haklı da olman gerekir.",
    "k.luckyreflex.lang": "Hızlı tepki ver – ama yalnızca doğruysa. 17 tur türü, makine silindirleri ve durmadan basanlar için tuzaklar.",
    "k.luckyreflex.s1": "Oda aç, kodu ilet – iki ile dört kişi.",
    "k.luckyreflex.s2": "Bütün yüzey düğmedir: herhangi bir yere dokun, bilgisayarda boşluk tuşu.",
    "k.luckyreflex.s3": "Her turda aynı türden beş görev gelir. İki ya da üçü uyar – geri kalanında doğru cevap hiç dokunmamaktır.",
    "k.luckyreflex.s4": "Erken bastın ya da yanlış göreve bastın: puan gitti. Yukarıdaki görüntüde ekran yeşil, oysa aranan turuncu.",
    "k.luckyreflex.s5": "17 ayrı tur türü, gözü kapalı sürekli basmanın işe yaramamasını sağlar.",

    "k.snake.kurz": "Bütün yılanlar tek tahtada. Hareket sunucuda işler, telefonda değil.",
    "k.snake.lang": "Ortak bir ızgarada bir ile altı yılan. Elmalar uzatır, duvarlar ve yabancı kuyruklar öldürür. Kaydırma kendi telefonunda olur, hesap merkezde yapılır – ki herkes aynı çarpışmayı görsün.",
    "k.snake.s1": "Oda aç, bağlantıyı ilet – iki ile altı kişi, herkes kendi telefonuyla. Tek başına da başlanır, o zaman herkesin bildiği Snake olur.",
    "k.snake.s2": "Oda sahibi kaç tur oynanacağını ayarlar.",
    "k.snake.s3": "Kaydırma ya da yön tuşları yönü değiştirir. Geri dönüş yoktur.",
    "k.snake.s4": "Elmalar on puan verir ve yılanı uzatır.",
    "k.snake.s5": "Duvar, yabancı yılan, kendi gövden – hepsi öldürür. En son hayatta kalan yirmi puan alır – tek başına oynarken bu yoktur.",
    "k.snake.s6": "Son turdan sonra genel sıralama görünür.",

    "k.revier.kurz": "Hiç durmayan bir dünya. Gir ve hemen sür – alan çevir ve elinde tut.",
    "k.revier.lang": "Oda yok, kod yok, tur sonu yok: sayfayı aç, sürmeye başla. Kendi bölgenin dışında arkanda iz bırakırsın – kendi bölgene dönünce çevrelediğin her yer senin olur. Yabancı bir izi kesen, onu oyundan çıkarır. Başparmağın nereye değerse kumanda kolu oraya oturur.",
    "k.revier.s1": "Bağlantıyı ilet ve aç – kimse beklemez, dünya çoktan işliyor. Sonradan gelen öylece katılır.",
    "k.revier.s2": "Ekranın herhangi bir yerine dokunup çek: kumanda kolu bundan sonra oradadır. Bırakmak dümdüz devam demektir. Bilgisayarda WASD ve yön tuşları çalışır.",
    "k.revier.s3": "Kendi bölgende sürdüğün sürece bir şey olmaz. Dışarıda arkanda bir iz sürüklersin.",
    "k.revier.s4": "Kendi bölgene dönünce izin çevrelediği her yer senin alanın olur – daha önce başkasına ait olanlar da.",
    "k.revier.s5": "Öldüren şeyler: kendi izin, dış duvar ve izinin üstünden geçen herkes. Yakalanan bütün bölgesini kaybeder.",
    "k.revier.s6": "İki buçuk saniye sonra küçük bir başlangıç karesiyle yine bir yerde belirirsin. Sağ üstte kimin dünyanın yüzde kaçını tuttuğu yazar.",
    "k.revier.s7": "Az kişi varsa botlar da sürer – ki dünya hiç boş kalmasın.",

    "k.wurm.kurz": "Enerji topla, büyü, kimsenin önüne çıkma. Dünya hep çalışır.",
    "k.wurm.lang": "Katıl ve hemen sürünmeye başla: her yerde enerji topları var, her biri seni uzatıp kalınlaştırır. Bir başkasının içine girersen enerjiye dağılırsın – o dağılmaz. İkinci parmak turbo verir, neredeyse üç kat hızlı ve o oranda pahalı. Yukarı doğru bir sınır yok.",
    "k.wurm.s1": "Adını yaz ve katıl – kimse beklemez, dünya çoktan işliyor. Sonradan gelen öylece katılır.",
    "k.wurm.s2": "Ekranın herhangi bir yerine dokunup çek: kumanda kolu bundan sonra oradadır. Bırakmak dümdüz devam demektir. Bilgisayarda WASD ve yön tuşları çalışır.",
    "k.wurm.s3": "Renkli toplar enerjidir. Her biri seni uzatır ve biraz kalınlaştırır – büyükleri daha çok verir ve onlar birinin az önce öldüğü yerde durur. Üst sınır yoktur: dayanan istediği kadar büyür, görüntü de onunla birlikte uzaklaşır.",
    "k.wurm.s4": "Ekrana ikinci parmak, sağ alttaki düğme ya da boşluk tuşu: turbo. Neredeyse üç kat hızlı, buna karşılık daha ağır döner ve sürekli enerji harcar; harcadığın arkanda yeniden düşer – oransal olarak, yani dev bir solucan bir yavrudan çok öder.",
    "k.wurm.s5": "Yabancı her gövde ve dış duvar öldürür – kendi gövden öldürmez. Sana çarpan enerjiye dağılır, ve onu hemen toplayabilirsin.",
    "k.wurm.s6": "İki saniye kadar sonra bir yerde yeniden küçük başlarsın. Sağ üstte kimin ne kadar enerjisi olduğu yazar.",
    "k.wurm.s7": "Dünya boş kalmasın diye botlar da sürünür. Her biri başka bir boyutta yemeyi bırakır – hepsi yakalanabilir.",

    "k.sudoku.kurz": "Dokuza dokuz, üç zorluk – ve her bulmacanın tek bir çözümü var.",
    "k.sudoku.lang": "Üretici her bulmacayı yeniden kurar ve boşaltırken sayar: çözücü iki çözüm bulursa sayı geri konur. Yani tahmine hiç gerek yoktur. Not kipi, hata göstergesi ve rekor süre ile.",
    "k.sudoku.s1": "Zorluk seç: kolay, orta ya da zor.",
    "k.sudoku.s2": "Kareye dokun, sonra altındaki tuş takımından sayıya.",
    "k.sudoku.s3": "✎ not kipini açar – sayı konunca kendiliğinden temizlenen küçük notlar.",
    "k.sudoku.s4": "Yanlış giriş kırmızıya döner. Hata sayısı yukarıda durur.",
    "k.sudoku.s5": "Her bulmacanın tek çözümü vardır; üretici bunu boşaltmadan sonra denetler.",
    "k.sudoku.s6": "Çözdün mü? Süre ve hatalar aşağıda durur, rekor tarayıcında kalır.",

    "k.wortgitter.kurz": "Beş harf, altı deneme, günde bir kelime – herkes için aynısı.",
    "k.wortgitter.lang": "Yeşil doğru, sarı başka yerde, gri hiç yok demektir. Denetim, Wortleger ile aynı CC0 kelime listesine göre yapılır; yalnızca gerçekten bilinen kelimelerle çözülür. Seri ve istatistik tarayıcında kalır.",
    "k.wortgitter.s1": "Beş harfli bir kelimeyi tahmin et, altı deneme.",
    "k.wortgitter.s2": "Yeşil: harf doğru yerde. Sarı: var ama başka yerde. Gri: hiç yok.",
    "k.wortgitter.s3": "Tekrarlanan harfler doğru sayılır – kelimede tek bir E varsa yalnızca bir E boyanır.",
    "k.wortgitter.s4": "Her gece yarısı yeni bir kelime gelir ve herkes aynısını alır.",
    "k.wortgitter.s5": "Sonunda sonucunu kare deseni olarak kopyalayabilirsin.",
    "k.wortgitter.s6": "Seri ve istatistik bu tarayıcıda kalır – hiçbiri bir sunucuya gitmez.",

    "k.patience.kurz": "Yedi sıra ve dört aslı olan Klondike. Sürüklemek yerine dokunmak.",
    "k.patience.lang": "Telefonda çalışsın diye kurulmuş solitaire klasiği: önce karta, sonra hedefe dokun – bir kart sütununda sürükle bırak kimsenin tutturabileceği bir şey değil. Bir ya da üç kart çekme, sonu toplamak için „Topla“ düğmesi.",
    "k.patience.s1": "Amaç: dört rengi de yukarıda astan papaza kadar üst üste dizmek.",
    "k.patience.s2": "Masada azalan sırayla ve renk değiştirerek dizilir – kırmızı siyahın, siyah kırmızının üstüne.",
    "k.patience.s3": "Önce karta, sonra hedefe dokun. Sütunun ortasındaki bir kart, altındakilerin hepsini birlikte götürür.",
    "k.patience.s4": "Boş yere yalnızca papaz konabilir.",
    "k.patience.s5": "Sol üstteki deste bir ya da üç kart çeker; boşaldıysa bir dokunuş onu yeniden çevirir.",
    "k.patience.s6": "„Topla“ sonunda yukarı uyan her şeyi yerleştirir.",

    "k.ameisen.kurz": "Kırıntı at ve bulunup yuvaya taşınmalarını izle. Sen yokken de çalışır.",
    "k.ameisen.lang": "Kumda bir yuva, dışarı yayılan bir koloni. Aralarına yem atarsın, karıncalar arar, bulur ve eve taşır – ve taşıyan bir koku izi bırakır, diğerleri de onun peşine düşer. Böylece tek bir buluş kısa sürede bir yola dönüşür. Aşağıda yuvada öğütülür, ondan madeni para çıkar, ve onun yeri dükkândır: daha çok karınca, daha güçlü çeneler, ikinci bir çıkış. Yuvan sana kalır ve sen bakmazken çalışmaya devam eder.",
    "k.ameisen.s1": "Açman yeter – ad yok, kod yok. İlk seferde üç karıncalı taze bir yuva alırsın; tarayıcın kimliği hatırlar ve her defasında aynı yuvaya dönersin.",
    "k.ameisen.s2": "Bir yere dokunmak kırıntı atar. Kese kendiliğinden dolar. Yuvanın kendi üstüne bir şey atamazsın – onu kimsenin taşımasına gerek olmazdı.",
    "k.ameisen.s3": "Karıncalar oraya buraya koşar ve yakınlarına geleni koklar. Aynı yere birkaç kırıntı at: o zaman yol değer, ve ilk taşıyanın koku izi diğerlerini peşinden sürükler.",
    "k.ameisen.s4": "Taşınan yem depoya girer. Aşağıdaki odada öğütülür, ve ondan sürekli para çıkar – oda ve koloni büyüdükçe daha hızlı. Depo dolduysa gelen kaybolur.",
    "k.ameisen.s5": "Dükkânda her basamak öncekinden pahalıdır: karıncalar, çeneler, bacaklar, duyargalar, koku izi, ikinci çıkış, oda, mantar bahçesi, kiler, tohum kesesi.",
    "k.ameisen.s6": "Sayfayı kapatırsan yuva çalışmayı sürdürür – ama o zaman kimse kırıntı atmaz. Yalnızca kendiliğinden düşenler toplanır: gece için yapılacak eklentiler <b>orman kenarı</b> ile <b>yaprak bitleri</b>, kiler de onların yeridir.",
    "k.ameisen.s7": "Bir noktada yeni bir yuva kurarsın: her şey baştan başlar, ama kraliçeler seninle gelir ve her teslimatı kalıcı olarak daha verimli kılar.",

    "k.wasserfarben.kurz": "Renkli katmanları şişeden şişeye dök, her şişede tek renk kalana kadar. Water-Sort bulmacası.",
    "k.wasserfarben.lang": "Şişelere karışık doldurulmuş dört ile on iki renk. Yalnızca aynı renk aynı rengin üstüne dökülebilir ve hiçbir şey kenardan taşmaz: yalnızca yarısı sığıyorsa gerisi yerinde kalır. Kolay görünür, kolay basamakta öyledir de – on iki renk ve iki boş şişeyle bir süre uğraşırsın. Her karışımın çözülebilir olduğu kanıtlıdır: üretici, sen görmeden önce onu kendisi çözer. Ad ve puanlar tarayıcıda kalır.",
    "k.wasserfarben.s1": "Basamağı seç: 4, 7, 10 ya da 12 renk. İki şişe her zaman boştur.",
    "k.wasserfarben.s2": "Bir şişeye dokun – en üstteki tek renkli blok kaldırılır. Sonra hedef şişeye dokun.",
    "k.wasserfarben.s3": "Yalnızca aynı rengin üstüne ya da boş şişeye dökülür. İçine dört katman sığar, fazlası asla.",
    "k.wasserfarben.s4": "Üstteki bloğun tamamı dökülür. Yalnızca bir kısmı sığıyorsa gerisi şişede kalır.",
    "k.wasserfarben.s5": "Geri, istediğin kadar hamleyi geri alır ve puan götürmez – hiç kullanmayan yirmi puan fazladan alır.",
    "k.wasserfarben.s6": "Bitti: her şişede tek bir renk kaldı. Puanlar basamağa ve az hamleye göre verilir; tarayıcıda adının altında birikmeye devam eder.",

    "k.schafstall.kurz": "Birbirinin yolunu kesen hayvanlarla dolu bir otlak. Dokun, koştur, it – hepsi ağıla girene kadar.",
    "k.schafstall.lang": "Her hayvan bir yöne bakar ve yalnızca oraya koşar: ya ilk engelin önüne kadar ya da otlaktan tamamen dışarı. Böylece dıştan içe doğru toplanır – ve gerektiği yerde itilir. İki koyun birlikte koşar, bir fil dörtlü bir blok kaplar ve yan yana iki boş şerit ister. Kurt yerinden hiç kımıldamaz ama menzilinde duran her şeye saldırır – yanından geçmek tehlikeli değildir. Hiçbiri geri geri gitmez, yani sıkışabilirsin: bunun için Geri ve Baştan var, ikisi de puan götürmez. Her otlak, hayvan başına tek hamleyle boşaltılabilir – üç yıldız tam da bunun içindir. Puanlar, tur ve yıldızlar tarayıcıda adının altında kalır; birkaç kişi tek cihazı paylaşabilir.",
    "k.schafstall.s1": "Adını yaz – ya da „Sonra“ de, o zaman Misafir oynar. Puanlar ada aittir ve bu tarayıcıda kalır.",
    "k.schafstall.s2": "Bir hayvana dokun: okunun gösterdiği yöne koşar – ya ilk engelin önüne kadar ya da otlaktan çıkıp ağıla.",
    "k.schafstall.s3": "En kısa yol dıştan içe doğrudur: her otlak, hayvan başına tek bir hamleyle boşaltılabilir. Üç yıldız bunun içindir.",
    "k.schafstall.s4": "İten sıkışabilir – hiçbiri geri geri gitmez. „Geri“ hamleleri geri alır, „Baştan“ otlağı yeniden kurar. İkisi de puan götürmez.",
    "k.schafstall.s5": "Kurt 🐺 hiç kımıldamaz – ama menzilinde (taralı kareler) duran biri gider ve tur baştan başlar. Yanından geçmek tehlikeli değildir.",
    "k.schafstall.s6": "4. turdan sonra iki koyun birlikte koşar, 6'dan sonra kayalar çıkar, 8'den sonra kurt gelir, 10'dan sonra kenar çitle kapanır, 12'den sonra yolda bir fil durur – iki kere iki hücre büyüklüğünde.",
    "k.schafstall.s7": "Hepsi ağılda: puanlar tura, artan hamlelere ve hıza göre, üstüne üç yıldıza kadar. Sonraki tur daha büyük ve daha kalabalıktır.",
    // --- Glückspilz ---
    "k.glueckspilz.kurz": "Para yalnızca bir düğmeden doğan bir oyun parası kumarhanesi: her basışta bir kuruş. On bir şans oyunu ve uydurma bir borsa onu geri alıyor.",
    "k.glueckspilz.lang": "Burada gerçek para dönmez – yatırma yok, çekme yok, alıp götürülecek hiçbir şey yok. Her şey büyük yeşil bir düğmeyle başlar: bir basış, bir kuruş. Hızlı basan hız çubuğunu yukarıda tutar ve daha çok alır; dükkânda her biri bir öncekinin üç katına mal olan basamaklar vardır, ki düğme asla gereksiz olmasın. Gece boyunca küçük bir tutar birikir. Kazanılan, on bir şans oyununda yakılabilir – Plinko, Mines, Crash, Dice, Limbo, Ejderha Kulesi, Flip, Elmaslar, Bars, Keno, Düşen Meyve – ya da fiyatları eğilimler, sakin ve çalkantılı dönemler ve haberler tanıyan sekiz uydurma şirketin borsasında. Orada kaldıraç yüz katına kadar ayarlanır; değer sıfıra düşerse, sen bakmıyorken bile pozisyon gider. Ödeme oranı her yerde %97'nin biraz altında ve her atış sonradan doğrulanabilir: sunucu tohumunun özeti önceden orada durur. Ad ve parolayla bir hesap bunun parçasıdır – onsuz kayıt, tarayıcı bir sonraki temizlikte silinirdi.",
    "k.glueckspilz.s1": "Hesap aç: ad ve parola, başka bir şey değil – e-posta yok, kurtarma yok. <b>18 yaş üstü</b>, ve içindeki her şey oyun parası.",
    "k.glueckspilz.s2": "Düğme tek kaynaktır: bir basış, bir kuruş. Hızlı basmak hız çubuğunu doldurur ve iki buçuk katına kadar öder.",
    "k.glueckspilz.s3": "Dükkânda beş basamak bekler: daha iyi bir başparmak, senin yerine basan bir cin, hız çubuğu için ateş hırsı, gece için bir çorap kumbara ve uğurlar için bir yonca tarhı. Her basamak öncekinin aşağı yukarı üç katı tutar.",
    "k.glueckspilz.s4": "Arada bir ekranda bir uğur uçar. Dokun: 🍀 ve 💰 hemen öder, ⚡ basış değerini üçe katlar, ⭐ her kazancı yarı yarıya artırır, 🎁 üç bedava bahis verir.",
    "k.glueckspilz.s5": "On bir oyun parayı geri alır: Plinko, Mines, Crash, Dice, Limbo, Ejderha Kulesi, Flip, Elmaslar, Bars, Keno, Düşen Meyve. Her yerde ortalama 100 avronun 97'ye yakını geri döner – yani uzun vadede kaybedilir, ve bir kumarhane tam olarak böyle kurulur.",
    "k.glueckspilz.s6": "Borsada sekiz uydurma şirket var. Fiyatlar yazı tura değil: eğilimler, sakin ve çalkantılı dönemler, haberler ve hepsini birden kımıldatan bir piyasa var. Kaldıraç 100'e kadar çıkar – ve değer sıfıra düşerse, sen bakmıyorken bile pozisyon gider.",
    "k.glueckspilz.s7": "Her atış doğrulanabilir: „Tablo“ altında, sen oynamadan önce sunucu tohumunun özeti durur. Aç, hesapla, yeni tohum al.",
  },

  en: {
    // --- Kopf der Seite ---
    "seite.titel": "Games – inf-zeus.de",
    "seite.beschreibung": "Twenty-nine browser games for 1 to 20 people. No install, no account.",
    "seite.h1": "Games",
    "seite.sub": "Twenty-nine browser games for 1 to 20 people. No download, no account – share the link, type a name, go.",

    // --- Suche - die drei Meldungen entstehen erst beim Tippen ---
    "suche.platz": "Search games – name, keyword, player count",
    "suche.label": "Search the games",
    "suche.keins": "No game found. Maybe it is spelled differently?",
    "suche.eins": "One game – press Enter to open it.",
    "suche.viele": "{n} of {alle} games.",

    // --- Die Kategorien ---
    "gruppe.beliebt.titel": "Played the most",
    "gruppe.beliebt.sub": "What sits up here is decided by the last four weeks – and it only changes when a game is opened markedly more often.",
    "gruppe.runde.titel": "Round the table, everyone on their own phone",
    "gruppe.runde.sub": "You sit together and talk; the phone only keeps score. One person opens a room, the others type in the code.",
    "gruppe.ruhe.titel": "Turn by turn, in peace",
    "gruppe.ruhe.sub": "One player moves, the others think along. No time pressure beyond the thinking time you set yourselves – or switch off.",
    "gruppe.tempo.titel": "Speed and skill",
    "gruppe.tempo.sub": "Cards, symbols, reflexes. Short rounds, harsh scores – everyone on their own device.",
    "gruppe.allein.titel": "Playing alone",
    "gruppe.allein.sub": "No room, no code, nobody to talk into it first. The puzzle games run entirely in the browser and need no connection once the page has loaded; Ameisen and Glückspilz keep running, because your colony and your account live on the server.",

    // --- Der Anleitungsdialog ---
    "dialog.zu": "Close",
    "dialog.bild": "A real screenshot from a game in progress.",
    "dialog.ablauf": "How a round goes",
    "dialog.spielen": "Play now →",
    "dialog.melden": "🐞 Report a bug in this game",
    "dialog.alt": "Screenshot from a game of {spiel}",

    // --- Bugreport-Zeile ---
    "melden.text": "Something broken? Report it – and see what has already been reported.",
    "melden.go": "Bug report →",

    // --- Spendenknopf und sein Dialog ---
    "spende.text": "The games are free and ad-free. If you like, you can help pay for the server.",
    "spende.go": "Support →",
    "spende.titel": "Thanks for trying!",
    "spende.eins": "Donations are not set up yet – the button was faster than I was. That you pressed it still means a lot.",
    "spende.zwei": "Come back later. Until then, the best contribution is bringing someone along to play.",
    "spende.zu": "You are welcome",

    // --- Fusszeile ---
    "fuss.text": "Runs on phones and computers, on the same Wi-Fi or across the net. One device opens the room, the others join with the code – everyone plays on their own.",
    "fuss.impressum": "Legal notice",
    "fuss.datenschutz": "Privacy",
    "fuss.rechtsprache": "The legal notice and privacy policy are only available in German.",

    // --- Was auf jeder Kachel steht ---
    "ui.spielen": "Play →",
    "ui.anleitung": "How to play",
    "ui.anleitungLabel": "How this game works",

    // --- Die Marken - nach Inhalt, nicht je Kachel ---
    "tag.p1_4": "1–4 players",
    "tag.p1_6": "1–6 players",
    "tag.p1_20": "1–20 players",
    "tag.p2_4": "2–4 players",
    "tag.p2_6": "2–6 players",
    "tag.p2_8": "2–8 players",
    "tag.p2_10": "2–10 players",
    "tag.p3_6": "3–6 players",
    "tag.p3_10": "3–10 players",
    "tag.p4_12": "4–12 players",
    "tag.allein": "solo",
    "tag.auchallein": "solo too",
    "tag.karten": "cards",
    "tag.offline": "offline",
    "tag.party": "party",
    "tag.knobeln": "puzzle",
    "tag.bluff": "bluff",
    "tag.ab18": "18+ optional",
    "tag.klassiker": "classic",
    "tag.laeuftimmer": "always running",
    "tag.rollen": "roles",
    "tag.woerter": "words",
    "tag.reaktion": "reflex",
    "tag.gegeneinander": "head to head",
    "tag.glueck": "luck &amp; nerve",
    "tag.wuerfel": "dice",
    "tag.trinkfrei": "alcohol-free",
    "tag.merken": "memory",
    "tag.augen": "eyes &amp; speed",
    "tag.tempo": "speed",
    "tag.taeglich": "daily",
    "tag.zusehen": "worth watching",

    // --- Die Kacheln ---
    "k.keep.kurz": "One machine, five rounds, and the clock gets tighter every time.",
    "k.keep.lang": "Spin, hold, combine. Five rounds that keep getting shorter – whoever lays the most valuable combination clears the table.",
    "k.keep.s1": "Open a room, pass the link on – two to four people. Alone works too: the start button waits for nobody.",
    "k.keep.s2": "Five rounds, each shorter than the last: from 90 seconds down to 25.",
    "k.keep.s3": "The reel spins by itself. After that you may redraw twice, deciding in between which symbols stay put.",
    "k.keep.s4": "Pick a valid combination from what is showing. The points depend on how rare it is – five of a kind pays twenty times a three of a kind, in every suit. The symbol only adds a little on top: hearts four percent, clover two per mille.",
    "k.keep.s5": "A second bar glows below the clock. It keeps falling and is charged by every combination, by rare ones more – five of a kind fills it completely. The hotter it stands, the bigger the multiplier, up to double.",
    "k.keep.s6": "Play fast and you keep it up there: a brisk move costs less heat than a three of a kind brings in. Once you find nothing more, the round is over.",

    "k.cardchaos.kurz": "Three card pyramids, ten rounds, and at the end you may gamble.",
    "k.cardchaos.lang": "Three pyramids, one timer, ten rounds. Whoever builds chains fastest clears the towers.",
    "k.cardchaos.s1": "Open a table, pass on the four-letter code – two to four people. Alone works too: then you play against your own best score.",
    "k.cardchaos.s2": "Everyone plays their own board at the same time, against the same clock.",
    "k.cardchaos.s3": "A face-up card goes if it is exactly one above or below the discard. King, ace and two wrap around.",
    "k.cardchaos.s4": "If nothing fits any more, you draw a new card – and that costs you your chain.",
    "k.cardchaos.s5": "The longer the chain, the higher the multiplier. After the round you may bet half your points on a coin flip.",

    "k.nochnie.kurz": "One person confesses, the rest get caught. The only game here where you talk instead of tap.",
    "k.nochnie.lang": "The game for the table: one person confesses, everyone else gets caught. No time pressure, no reflexes – just talking. Harmless cards are the default; the table unlocks 18+ itself.",
    "k.nochnie.s1": "Open a room, pass the link on – two to eight people, each with their own phone.",
    "k.nochnie.s2": "Each round the server picks somebody. They say a sentence out loud that starts with “I have never …” and is true for them.",
    "k.nochnie.s3": "If nothing comes to mind, they tap “I can't think of anything” and get a card – which everybody then sees.",
    "k.nochnie.s4": "Everyone else confesses: “I have” or “never”. Nothing is revealed until all have tapped, so nobody copies.",
    "k.nochnie.s5": "Whoever got caught stands in red on the list. Whether that turns into a sip, the story behind it or nothing at all is up to you – the game only counts.",
    "k.nochnie.s6": "The host sets what is on the cards: harmless, mixed or 18+ only. Before the 18+ cards, every device asks once.",

    "k.minenfeld.kurz": "Read the numbers, plant flags, do not guess. The first tap is always safe.",
    "k.minenfeld.lang": "The classic, brought to the phone: tap to uncover, press and hold to plant a flag. Three sizes, a best time for each. Runs entirely in the browser, without an account and without a server.",
    "k.minenfeld.s1": "Pick a size: small, medium or large.",
    "k.minenfeld.s2": "Tapping uncovers a square. The first tap never hits a mine.",
    "k.minenfeld.s3": "Every number says how many mines lie in the eight squares around it.",
    "k.minenfeld.s4": "Press and hold to plant a flag – on a computer, right-click works too.",
    "k.minenfeld.s5": "Tapping an uncovered number opens everything around it, once enough flags are set.",
    "k.minenfeld.s6": "All squares without a mine uncovered: done. Your best time stays in your browser.",

    "k.amehesten.kurz": "One question, everyone points at once. The reveal is what starts the conversation.",
    "k.amehesten.lang": "One question, and everyone points at a person at the same time. Nothing is revealed until all have chosen – then bars show who was meant how often, and by whom. The quickest start of them all. Harmless questions are the default; the table unlocks 18+ itself.",
    "k.amehesten.s1": "Open a room, pass the link on – three to ten people, each with their own phone.",
    "k.amehesten.s2": "Each round brings a question completing the phrase “Which of you …?”. Below it stand all the names in the room.",
    "k.amehesten.s3": "Everyone taps at the same time on whoever it fits best – including themselves, if the host allowed it.",
    "k.amehesten.s4": "As long as not everyone is done, you can change your mind. Your own choice stays visible, the others' do not.",
    "k.amehesten.s5": "Nothing is revealed until everyone has chosen. Then come the bars: who got how many votes – and from whom.",
    "k.amehesten.s6": "Every vote is a point for the person chosen; whoever leads a round gets a crown. At the end it shows who was talked about most.",
    "k.amehesten.s7": "Four decks: Harmless works at the family table, Cheeky aims at quirks and embarrassments, Mixed is both – and 18+ is a deck of its own that the host has to unlock.",

    "k.imposter.kurz": "Everyone knows the word. Except one – and they have to fake it.",
    "k.imposter.lang": "Everyone gets the same word – except one. The phone only shows the word and organises nothing else: talking in turn, pointing at each other and arguing happens at the table. In the second mode everyone gets a word, but one of them differs – and the person it hits does not know it themselves. The longest evening of them all.",
    "k.imposter.s1": "Open a room, pass the link on – three to ten people at one table, each with their own phone. No readying up: whoever is in the room is in.",
    "k.imposter.s2": "Put the phone down, took a call, battery dead? Your seat stays reserved. Whoever comes back is the same person again – same card, same round.",
    "k.imposter.s3": "The host taps “Deal”. Everyone gets the same word, say “sandpaper”. One person does not – they only see that they are the imposter. That is all they get.",
    "k.imposter.s4": "The card lies <b>face down</b>: to look, push the lid up and hold it; letting go closes it again. The phone can stay open – in fact it should, or the connection drops.",
    "k.imposter.s5": "At the top it says <b>who starts and which way it goes</b>. Everyone reads the same sentence; the phone still tells nobody that it is their turn – the table keeps track.",
    "k.imposter.s6": "In turn, everyone says one word out loud about it.",
    "k.imposter.s7": "Not too obvious, or the imposter catches on at once – but not too vague either, or they will take you for the imposter.",
    "k.imposter.s8": "At the end you point at each other. Loudly, all at once, however you like. The phone does not vote and keeps no score.",
    "k.imposter.s9": "The host taps “Reveal”: everyone sees who it was and what the word was. Then they deal again.",
    "k.imposter.s10": "<b>Second mode, “Two Words”:</b> everyone gets a word, but one of them is a different one – museum for most, brothel for one. Nobody knows who differs, not even the one who does. Everyone talks in good faith, and it takes a while before something stops adding up.",
    "k.imposter.s11": "The pairs are deliberately odd: the descriptions fit both, the meanings lie far apart. Harmless is the default, the host unlocks 18+ – and every device asks once before that.",

    "k.maexchen.kurz": "You roll dice so that you can lie about them. Two dice, one cup, and only you see underneath.",
    "k.maexchen.lang": "Two dice under the cup, and only you can see them. Announce what you supposedly have – higher than the player before you. The next one believes it or lifts the cup. Somebody always loses a life.",
    "k.maexchen.s1": "Open a room, pass the link on – two to eight people, each with their own phone.",
    "k.maexchen.s2": "Whoever is up shakes the cup. The two dice appear on their screen only – the server tells nobody else.",
    "k.maexchen.s3": "Then they announce what they supposedly have. The announcement must beat the previous one; whether it matches their actual roll is their business.",
    "k.maexchen.s4": "The next player decides: “I believe you” – then they roll themselves and must announce something higher. Or “I don't believe it” – then the cup comes up.",
    "k.maexchen.s5": "When the cup comes up, one side always loses a life: the announcer if they lied, the doubter if they did not.",
    "k.maexchen.s6": "The ranking: 31 is the worst, then up to 65, above that the doubles. Right at the top sits 21 – the Mäxchen. It cannot be beaten, only doubted, and that costs double.",
    "k.maexchen.s7": "Whoever runs out of lives is out. The last one at the table wins.",

    "k.flasche.kurz": "The bottle decides whose turn it is – on every phone at the same time.",
    "k.flasche.lang": "In turn, one person spins the bottle – it spins on every screen at the same time and stops on the same person for everyone. Then truth or dare. Or just the bottle, if that is enough for you.",
    "k.flasche.s1": "Open a room, pass the link on – three to ten people, each with their own phone.",
    "k.flasche.s2": "In turn, one person spins the bottle. It spins for everyone at once and stops on the same person everywhere – the server picks the target, not your device.",
    "k.flasche.s3": "Whoever it hits is up. In “spin only” mode the round ends right there; what happens next is up to you.",
    "k.flasche.s4": "Otherwise the person picks between truth and dare and gets a card. Everyone sees it.",
    "k.flasche.s5": "If the card does not fit, one tap brings another. Skipping is always allowed and costs nothing – it is only counted.",
    "k.flasche.s6": "The cards come without alcohol, without sex and without physical contact. “Cheeky” here means embarrassing, not suggestive, and every dare can be done sitting down.",
    "k.flasche.s7": "At the end it shows who the bottle hit most often.",

    "k.werwolf.kurz": "At night the wolves take someone. By day the village talks – and gets it wrong.",
    "k.werwolf.lang": "Four to twelve people, five roles: werewolf, villager, seer, witch, Cupid. The server plays narrator, you only have to talk and suspect each other.",
    "k.werwolf.s1": "Open a room, pass the link on – it starts at four people, it gets good at six.",
    "k.werwolf.s2": "Everyone gets their role card on their own phone and confirms it.",
    "k.werwolf.s3": "At night the server wakes the wolves, then the seer and the witch. Whoever is not up puts the phone down.",
    "k.werwolf.s4": "In the morning the server says who did not survive the night – and which role they had.",
    "k.werwolf.s5": "By day you talk, out loud and in the room. Then everyone votes on who hangs.",
    "k.werwolf.s6": "The village wins once the wolves are gone, the wolves win once they outnumber the rest. The lovers win as a pair.",

    "k.becher.kurz": "Five dice each, under the cup. Bids cover everything that might be on the table.",
    "k.becher.lang": "A relative of Mäxchen, but everyone has their own dice: “four fives” means there are at least four fives – no matter whose. Ones are wild. Whoever does not believe it calls, and someone loses a die.",
    "k.becher.s1": "Open a room, pass the link on – two to six people.",
    "k.becher.s2": "Everyone gets five dice, visible on their own phone only.",
    "k.becher.s3": "Bids go round: a count and a face, always higher than the bid before.",
    "k.becher.s4": "Ones count as wild for every face – nobody bids on ones themselves.",
    "k.becher.s5": "Instead of bidding you can call. Then everyone lifts their cup and the dice are counted.",
    "k.becher.s6": "Whoever was wrong loses a die. Whoever has none left is out.",

    "k.kingscup.kurz": "One card, one rule, the whole table joins in. Alcohol-free by default.",
    "k.kingscup.lang": "In turn, one person draws a card, and everyone sees the same rule on their phone. The alcohol-free version is the default: same cards, small tasks instead of sips. The fourth king ends it.",
    "k.kingscup.s1": "Open a room, pass the link on – two to ten people.",
    "k.kingscup.s2": "The host picks the version: alcohol-free (default) or with sips.",
    "k.kingscup.s3": "In turn, one person draws a card. Everyone sees it and its rule at the same time.",
    "k.kingscup.s4": "Numbers are short tasks; jack, queen and ace set rules that keep running.",
    "k.kingscup.s5": "Once the rule is done, whoever drew taps “next”.",
    "k.kingscup.s6": "The fourth king ends the round.",

    "k.wortleger.kurz": "Letters with values on a board with bonus squares. Words are checked against a word list, not against your friends' patience.",
    "k.wortleger.lang": "Seven tiles on your rack, a 13×13 board with bonus squares. Lay words, cross the others' and take the triple squares before somebody else does.",
    "k.wortleger.s1": "Open a room, pass the code on – two to four people. Everyone draws seven tiles that only they can see.",
    "k.wortleger.s2": "Players take turns. Tap a tile on your rack, tap an empty square – that places it. Tapping again takes it back.",
    "k.wortleger.s3": "The first word must go through the star in the middle. After that every new word has to connect to something already on the board.",
    "k.wortleger.s4": "One move places tiles in a single row or column, without gaps. Everything that comes out of it – crosswise too – has to be a word.",
    "k.wortleger.s5": "Words are checked against a German word list with 488&nbsp;344 entries. Umlauts have their own tiles, ß is written as SS.",
    "k.wortleger.s6": "Bonus squares double or triple a letter or a word – but only on the move that covers them.",
    "k.wortleger.s7": "Using all seven tiles in one move is worth 40 extra points. Whoever finds nothing swaps tiles or passes.",
    "k.wortleger.s8": "Two blanks lie in the bag. They stand in for any letter but count zero.",
    "k.wortleger.s9": "Whoever empties their rack first once the bag is empty gets what the others still hold on top – and they subtract their remaining tiles.",

    "k.luegen.kurz": "Play face down and announce it. Whoever calls it turns them over – somebody takes the pile.",
    "k.luegen.lang": "The whole deck is dealt out, everyone wants to get rid of their cards. Cards go down face down, and the announced rank climbs by one every round. Nobody can see whether you really played three eights.",
    "k.luegen.s1": "Open a room, pass the link on – three to six people, each with their own phone.",
    "k.luegen.s2": "All cards are dealt out. Whoever runs out first wins.",
    "k.luegen.s3": "In turn, everyone plays one to four cards face down and announces what they supposedly are.",
    "k.luegen.s4": "The announced rank climbs by one each round – you have to play what is due, whether you hold it or not.",
    "k.luegen.s5": "Whoever does not believe it taps “Lie!”. Cards up: if the player lied, they take the pile, otherwise the doubter does.",
    "k.luegen.s6": "An ace is not passed on – after it, the next player starts a new sequence.",

    "k.maumau.kurz": "Follow the suit or the number. Seven draws, eight skips, jack calls the suit.",
    "k.maumau.lang": "The public-domain classic with 32 cards. The host sets which special rules apply beforehand – and whoever is down to one card has to say “Mau”, or it costs two.",
    "k.maumau.s1": "Open a room, pass the link on – two to six people.",
    "k.maumau.s2": "The host switches the special rules on or off: seven draws two, eight skips, jack calls the suit.",
    "k.maumau.s3": "Everyone gets five cards. You follow the suit or the number of the top card.",
    "k.maumau.s4": "If nothing fits, you draw a card and your turn is over.",
    "k.maumau.s5": "Whoever gets down to one card taps “Mau!” beforehand. Forgetting costs two cards.",
    "k.maumau.s6": "Whoever empties their hand first wins; the others count what is left.",

    "k.schwimmen.kurz": "Three cards, three lives. Whoever has the least loses one.",
    "k.schwimmen.lang": "31 in one suit, three cards in hand, three face up in the middle. Swap, pass or knock – and hope somebody else has less than you.",
    "k.schwimmen.s1": "Open a room, pass the link on – two to six people.",
    "k.schwimmen.s2": "Everyone gets three cards, three more lie face up in the middle.",
    "k.schwimmen.s3": "What counts is the highest total in one suit: 7 to 10 as printed, jack to king ten, ace eleven. Three of the same number count 30.5.",
    "k.schwimmen.s4": "Whoever is up swaps one card, all three – or passes.",
    "k.schwimmen.s5": "Knocking means: everyone else gets one more turn, then the cards come up.",
    "k.schwimmen.s6": "Whoever has the least loses a life. After the third you are swimming; the next time you are out.",

    "k.paare.kurz": "One board, everyone watches, one person plays. Find two of a kind and you go again.",
    "k.paare.lang": "The memory game for a group: one shared board, everyone sees it on their own phone. Not even your browser knows the face-down cards – looking at the source gets you nowhere. Eight, fifteen or twenty-four pairs, and it works alone too.",
    "k.paare.s1": "Open a room, pass the link on – up to six people, alone works too.",
    "k.paare.s2": "The host picks the size: 8, 15 or 24 pairs.",
    "k.paare.s3": "Whoever is up turns two cards over. Everyone sees the same board at the same time.",
    "k.paare.s4": "If they match, they are yours – and you go again.",
    "k.paare.s5": "If they do not, they stay up for a moment so everyone can remember where they were.",
    "k.paare.s6": "Whoever has the most pairs at the end wins.",

    "k.cubes.kurz": "A full grid with your colour in it. You cannot tap anybody else's.",
    "k.cubes.lang": "Everyone gets a colour. The grid is always full and keeps changing – hit your own before they are gone. Three rounds, each with a new nasty twist.",
    "k.cubes.s1": "Open a room, pass the code on – two to six people. Everyone gets their own colour.",
    "k.cubes.s2": "Everyone sees the same grid. You can only tap the squares in your colour; the others are pale and do not react.",
    "k.cubes.s3": "The grid is always full – every gap is filled again at once, and half of it belongs to the others. Finding your own is half the job.",
    "k.cubes.s4": "<b>Round 1 – Tap:</b> your squares appear and disappear again by themselves. Hit them in time and the point is yours. The bar at the bottom shows how long one stays.",
    "k.cubes.s5": "<b>Round 2 – Multiple:</b> the same, but every square needs two to four hits. Points only come with the last one – a half-cleared square counts for nothing.",
    "k.cubes.s6": "<b>Round 3 – Plus and minus:</b> now there are numbers in them, negative ones too. Tap the positive, leave the negative: they go away by themselves.",
    "k.cubes.s7": "The negative ones look like the positive ones – only the number gives them away. Which is exactly why you grab the wrong one in the heat of it.",
    "k.cubes.s8": "Nobody can tap your minus square for you – the server decides that, not the politeness of the others.",
    "k.cubes.s9": "At the end the points from all rounds are added up.",

    "k.seconds.kurz": "Two cards, always exactly one symbol in common. Find it first.",
    "k.seconds.lang": "Your card and the one in the middle share exactly one symbol. Whoever taps it first takes the point.",
    "k.seconds.s1": "Open a room, pass the link on – two to four people.",
    "k.seconds.s2": "One card lies in the middle, your own in front of you.",
    "k.seconds.s3": "The two always have exactly one symbol in common – never more, never less. That is not luck, it is built into the deck.",
    "k.seconds.s4": "Whoever taps it first on their own card takes the point, and the next card comes straight away.",
    "k.seconds.s5": "A wrong tap means a second and a half locked out while the others play on. Whoever reaches the target score first wins.",

    "k.luckyreflex.kurz": "Being fast is not enough – you also have to be right.",
    "k.luckyreflex.lang": "React fast – but only when it is right. 17 kinds of round, slot-machine reels and traps for anyone who just keeps tapping.",
    "k.luckyreflex.s1": "Open a room, pass the code on – two to four people.",
    "k.luckyreflex.s2": "The whole surface is the button: tap anywhere, or press space on a computer.",
    "k.luckyreflex.s3": "Each round brings five tasks of the same kind. Two or three of them fit – for the rest, holding still is the right answer.",
    "k.luckyreflex.s4": "Tapped too early or on the wrong task: point gone. In the picture above the screen is green, but orange is what was asked for.",
    "k.luckyreflex.s5": "17 different kinds of round make sure that blind tapping gets you nowhere.",

    "k.snake.kurz": "All the snakes on one board. The movement runs on the server, not on the phone.",
    "k.snake.lang": "One to six snakes on a shared grid. Apples make you longer, walls and other tails are fatal. You swipe on your own phone, the maths happens centrally – so everyone sees the same crash.",
    "k.snake.s1": "Open a room, pass the link on – two to six people, each with their own phone. Starting alone works too, and then it is the Snake everybody knows.",
    "k.snake.s2": "The host sets how many rounds are played.",
    "k.snake.s3": "Swipes or arrow keys change direction. No turning back on yourself.",
    "k.snake.s4": "Apples give ten points and make the snake longer.",
    "k.snake.s5": "Wall, another snake, your own body – all fatal. Whoever is last alive gets twenty points – playing alone, there are none.",
    "k.snake.s6": "After the last round the overall score is shown.",

    "k.revier.kurz": "A world that never stops. Walk in and ride along at once – enclose ground and keep it.",
    "k.revier.lang": "No room, no code, no end of round: open the page and you are driving. Outside your own territory you drag a trail behind you – back inside, everything you enclosed becomes yours. Cross someone else's trail and they are out. Your thumb taps anywhere, and that is where the joystick sits.",
    "k.revier.s1": "Pass the link on and open it – nobody has to wait, the world is already running. Whoever arrives later simply joins in.",
    "k.revier.s2": "Tap anywhere on the screen and drag: from then on an invisible joystick sits there. Letting go means carrying straight on. On a computer, WASD and the arrow keys work.",
    "k.revier.s3": "Nothing happens while you drive on your own ground. Outside it, you drag a trail behind you.",
    "k.revier.s4": "Back in your own territory, everything the trail enclosed becomes your ground – including what belonged to somebody else before.",
    "k.revier.s5": "Fatal: your own trail, the outer wall, and anyone who drives across your trail. Whoever gets caught loses their whole territory.",
    "k.revier.s6": "After two and a half seconds you are back somewhere with a small starting square. Top right it shows who currently holds what percentage of the world.",
    "k.revier.s7": "When few people are around, bots drive along – so the world is never empty.",

    "k.wurm.kurz": "Collect energy, grow, stay out of everyone's way. The world is always running.",
    "k.wurm.lang": "Sign in and start crawling at once: energy orbs lie everywhere, each one makes you longer and thicker. Crawl into somebody else and you fall apart into energy – they do not. A second finger gives you turbo, nearly three times as fast and priced accordingly. There is no ceiling.",
    "k.wurm.s1": "Type a name and sign in – nobody has to wait, the world is already running. Whoever arrives later simply joins in.",
    "k.wurm.s2": "Tap anywhere on the screen and drag: from then on an invisible joystick sits there. Letting go means carrying straight on. On a computer, WASD and the arrow keys work.",
    "k.wurm.s3": "The coloured orbs are energy. Each one makes you longer and a little thicker – big ones give more, and they lie where somebody just died. There is no upper limit: last long enough and you grow as large as you like, with the view zooming out along with you.",
    "k.wurm.s4": "A second finger on the screen, the button at the bottom right or the space bar: turbo. Nearly three times as fast, but it turns more sluggishly and constantly burns energy, which falls out again behind you – proportionally, so a giant pays more than a hatchling.",
    "k.wurm.s5": "Every other body and the outer wall are fatal – your own is not. Whoever crawls into you falls apart into energy, and you can collect it right away.",
    "k.wurm.s6": "After a good two seconds you start again somewhere, small. Top right it shows who currently has how much energy.",
    "k.wurm.s7": "Bots crawl along so the world is never empty. Each stops eating at a different size – and all of them can be caught.",

    "k.sudoku.kurz": "Nine by nine, three levels – and every puzzle has exactly one solution.",
    "k.sudoku.lang": "The generator builds every puzzle from scratch and checks as it hollows it out: if the solver finds two solutions, the digit goes back in. So guessing is never needed. With pencil mode, mistake count and best time.",
    "k.sudoku.s1": "Pick a level: easy, medium or hard.",
    "k.sudoku.s2": "Tap a cell, then the number on the pad below.",
    "k.sudoku.s3": "✎ switches on pencil mode – small notes that clear themselves up when you place a digit.",
    "k.sudoku.s4": "A wrong entry turns red. The number of mistakes is shown at the top.",
    "k.sudoku.s5": "Every puzzle has exactly one solution; the generator verifies that after hollowing it out.",
    "k.sudoku.s6": "Solved? Time and mistakes are at the bottom, the best time stays in your browser.",

    "k.wortgitter.kurz": "Five letters, six tries, one word a day – the same one for everybody.",
    "k.wortgitter.lang": "Green means right, yellow means elsewhere, grey means not at all. Guesses are checked against the same CC0 word list as Wortleger; you only solve it with words people actually know. Streak and statistics stay in your browser.",
    "k.wortgitter.s1": "Guess a five-letter word, six tries.",
    "k.wortgitter.s2": "Green: the letter is in the right place. Yellow: it occurs, but elsewhere. Grey: it does not occur.",
    "k.wortgitter.s3": "Repeated letters are counted correctly – if the word has only one E, only one E is coloured.",
    "k.wortgitter.s4": "Every midnight brings a new word, and everybody gets the same one.",
    "k.wortgitter.s5": "At the end you can copy your result as a pattern of squares.",
    "k.wortgitter.s6": "Streak and statistics stay in this browser – none of it goes to a server.",

    "k.patience.kurz": "Klondike with seven columns and four aces. Tapping instead of dragging.",
    "k.patience.lang": "The solitaire classic, built so it works on a phone: tap the card first, then the target – nobody hits drag and drop inside a column of cards. Draw one or three, and “Tidy up” for the endgame.",
    "k.patience.s1": "The goal: stack all four suits at the top, from ace to king.",
    "k.patience.s2": "On the table you build downwards in alternating colours – red on black, black on red.",
    "k.patience.s3": "Tap the card first, then the target. A card in the middle of a column takes everything below it along.",
    "k.patience.s4": "Only a king may go on an empty space.",
    "k.patience.s5": "The pile at the top left draws one or three cards; once it is empty, a tap turns it over again.",
    "k.patience.s6": "“Tidy up” plays everything that fits at the top, for the endgame.",

    "k.ameisen.kurz": "Drop crumbs and watch them being found and carried home. Keeps running while you are away.",
    "k.ameisen.lang": "A mound in the sand, a colony swarming out. You throw food in between, the ants search for it, find it and carry it home – and whoever carries lays a scent trail the others follow. One find turns into a road before long. Down in the nest it is broken up, that produces coins, and coins belong in the shop: more ants, stronger jaws, a second exit. Your colony stays yours and keeps working while you are not looking.",
    "k.ameisen.s1": "Just open it – no name, no code. The first time you get a fresh mound with three ants; your browser remembers the id, and you land in the same colony every time.",
    "k.ameisen.s2": "Tapping anywhere drops a crumb. The pouch refills by itself. You cannot drop anything on the mound itself – nobody would have to carry that.",
    "k.ameisen.s3": "The ants run this way and that and smell whatever comes near them. Drop several crumbs in the same place: then the trip is worth it, and the first carrier's scent trail pulls the others along.",
    "k.ameisen.s4": "Food that is carried in goes into the store. Down in the chamber it is broken up, and that yields coins continuously – faster the bigger the chamber and the colony. If the store is full, anything more is lost.",
    "k.ameisen.s5": "In the shop every level costs more than the one before: ants, jaws, legs, antennae, scent trail, a second exit, chamber, fungus garden, larder, seed pouch.",
    "k.ameisen.s6": "Close the page and the colony keeps working – but then nobody drops crumbs. Only what falls by itself is collected: <b>forest edge</b> and <b>aphids</b> are the upgrades for the night, and the larder is where it goes.",
    "k.ameisen.s7": "At some point you found a new mound: everything starts over, but the queens come along and make every delivery permanently richer.",

    "k.wasserfarben.kurz": "Pour coloured layers from bottle to bottle until each holds a single colour. The water sort puzzle.",
    "k.wasserfarben.lang": "Four to twelve colours, layered into bottles in a jumble. You may only pour like onto like, and nothing ever goes over the rim: if only half of it fits, the rest stays put. Sounds simple, and on the easy level it is – with twelve colours and two free bottles you will be sorting for a while. Every mixture is provably solvable: the generator solves it itself before you ever see it. Name and points stay in the browser.",
    "k.wasserfarben.s1": "Pick a level: 4, 7, 10 or 12 colours. Two bottles are always free.",
    "k.wasserfarben.s2": "Tap a bottle – its topmost block of one colour is lifted. Then tap the target bottle.",
    "k.wasserfarben.s3": "You may only pour onto the same colour or into an empty bottle. Four layers fit in, never more.",
    "k.wasserfarben.s4": "The whole top block is poured. If only part of it fits, the rest stays in the bottle.",
    "k.wasserfarben.s5": "Undo takes back as many moves as you like and costs no points – finish without it and you get twenty extra.",
    "k.wasserfarben.s6": "Done: every bottle holds a single colour. Points come per level and for using few moves; they keep adding up under your name in the browser.",

    "k.schafstall.kurz": "A pasture full of animals getting in each other's way. Tap, let them run, push – until they are all in the pen.",
    "k.schafstall.lang": "Every animal faces one direction and only runs that way: up to the next obstacle, or clean out of the pasture. So you clear from the outside in – and push where you have to. Two sheep run as a team, an elephant takes up a block of four and needs two clear lanes side by side. The wolf never moves an inch, but it snaps at anything that comes to a stop within its reach – running past is safe. Nothing runs backwards, so you can get stuck: that is what Undo and Restart are for, and neither costs points. Every pasture is provably clearable with one move per animal – that is exactly what the three stars are for. Points, round and stars stay under your name in the browser; several people can share one device.",
    "k.schafstall.s1": "Type a name – or tap “Later”, and Guest plays. The points belong to the name and stay in this browser.",
    "k.schafstall.s2": "Tap an animal: it runs in the direction its arrow points – up to the next obstacle, or out of the pasture and into the pen.",
    "k.schafstall.s3": "The shortest way is from the outside in: every pasture can be cleared with a single move per animal. That is what the three stars are for.",
    "k.schafstall.s4": "Push things around and you can get stuck – nothing runs backwards. “Undo” takes moves back, “Restart” sets the pasture up again. Neither costs points.",
    "k.schafstall.s5": "The wolf 🐺 never moves – but whoever comes to a stop within its reach (the hatched squares) is gone, and the round starts over. Running past is safe.",
    "k.schafstall.s6": "From round 4 two sheep run as a team, from 6 there are rocks about, from 8 the wolf turns up, from 10 the edge is fenced in, from 12 an elephant stands in the way – two by two cells in size.",
    "k.schafstall.s7": "All in the pen: points by round, moves saved and speed, plus up to three stars. The next round is bigger and fuller.",
    // --- Glückspilz ---
    "k.glueckspilz.kurz": "A play-money casino where money only comes from one button: one cent per press. Eleven games of chance and an invented stock market take it back off you.",
    "k.glueckspilz.lang": "No real money runs here – there is no deposit, no withdrawal and nothing you could take with you. Everything starts at one big green button: one press, one cent. Press fast and the streak bar stays up and pays more; the shop sells levels whose price triples with each one, so the button never becomes pointless. Overnight a small amount piles up. What you earn can then be gambled away in eleven games – Plinko, Mines, Crash, Dice, Limbo, Dragon Tower, Flip, Diamonds, Bars, Keno, Windfall – or on a market of eight invented firms whose prices know trends, calm and wild stretches and news. There the leverage goes up to a hundred; if the value hits zero the position is gone, even while nobody is looking. The payout rate sits just under 97 % everywhere, and every single roll can be verified afterwards: the hash of the server seed is shown beforehand. An account with a name and a password is part of it – without one the save would be gone with the next cleared browser.",
    "k.glueckspilz.s1": "Create an account: name and password, nothing else – no e-mail, no recovery. <b>18+</b>, and everything inside is play money.",
    "k.glueckspilz.s2": "The button is the only source: one press, one cent. Pressing fast fills the streak bar and pays up to two and a half times as much.",
    "k.glueckspilz.s3": "Five levels wait in the shop: a better thumb, a brownie that presses along, burning zeal for the streak bar, a sock drawer for the night and a clover patch for the charms. Each level costs roughly three times the last.",
    "k.glueckspilz.s4": "Now and then a charm flies across the screen. Tap it: 🍀 and 💰 pay out at once, ⚡ triples the press value, ⭐ raises every win by half, 🎁 gives three free bets.",
    "k.glueckspilz.s5": "Eleven games take the money back: Plinko, Mines, Crash, Dice, Limbo, Dragon Tower, Flip, Diamonds, Bars, Keno, Windfall. Everywhere just under 97 of every 100 euros come back on average – so in the long run you lose, and that is exactly how a casino is built.",
    "k.glueckspilz.s6": "The market has eight invented firms. The prices are no coin flip: there are trends, calm and wild stretches, news, and a market that moves everything at once. Leverage goes up to 100 – and if the value hits zero the position is gone, even while you are not looking.",
    "k.glueckspilz.s7": "Every roll can be verified: under „Board“ the hash of the server seed is shown before you play. Reveal it, recompute, get a new seed.",
  },
};
